# test-mods/rust/simple-utility-mod/Cargo.toml
[package]
name = "simple-utility-mod"
version = "0.1.0"
edition = "2024"
workspace = "../../../"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mod-api = { path = "../../../sandyloader/crates/mod-api" }
