[package]
name = "jni-bridge"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "JNI bridge for SandyLoader"

[dependencies]
jni = "0.21.1"
log = "0.4.20"
thiserror = "1.0.50"
